### ISSUE TITLE
does not work with Ruby 1.9 ( 0.3 )

### ISSUE THREAD

**Issue by wtnabe** [wtnabe/ical2gcal#3]
error message is:

```
lib/ical2gcal.rb:24:in `run': undefined method `each' for #<String:0x17cb68> (NoMethodError) from ./bin/ical2gcal:5:in `<main>'
```
